Add kaniko-executer image
kyma-project/third-party-images pull request #123
Opened 2021-09-16 13:02 UTC by moelsayed

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2021-09-17 09:07 UTC, moelsayed commented
/test pre-main-third-party-images-protecode-guard

2021-09-17 10:48 UTC, adamwalach commented
/retest

2021-09-17 11:10 UTC, Halamix2 commented
/test pre-main-tpi-kaniko-executer

2021-09-17 11:13 UTC, adamwalach commented
/test pre-main-tpi-kaniko-executer

2021-09-17 11:16 UTC, Halamix2 commented
/test pre-main-tpi-kaniko-executer

2021-09-17 11:43 UTC, moelsayed commented
/retest

2021-09-18 00:05 UTC, moelsayed commented
/retest

2021-09-18 00:17 UTC, moelsayed commented
/retest

2021-09-18 00:19 UTC, moelsayed commented
/retest

2021-09-18 00:27 UTC, moelsayed commented
/retest

2021-09-20 06:41 UTC, moelsayed commented
/retest

2021-09-20 07:23 UTC, moelsayed commented
/retest

2021-09-20 07:30 UTC, moelsayed commented
/test pre-main-third-party-images-protecode-guard

2021-09-20 12:09 UTC, pPrecel submitted a review, later dismissed
/meow LGTM

2021-09-20 14:07 UTC, NHingerl requested changes

2021-09-20 14:07 UTC, NHingerl commented on kaniko-executer/README.md
> +This folder contains the kaniko-executer image that is based on the official [here](https://github.com/GoogleContainerTools/kaniko/blob/v1.6.0/deploy/Dockerfile).
```suggestion
This folder contains the custom kaniko-executer image that is based on the official [image](https://github.com/GoogleContainerTools/kaniko/blob/v1.6.0/deploy/Dockerfile).
```

2021-09-20 14:07 UTC, NHingerl commented on kaniko-executer/Dockerfile
> +#This arg is passed by docker buildx & contains the platform info in the form linux/amd64, linux/ppc64le etc.
```suggestion
#This arg is passed by docker buildx and contains the platform info in the form linux/amd64, linux/ppc64le etc.
```

2021-09-20 14:46 UTC, a-thaler approved these changes

2021-09-20 15:14 UTC, NHingerl approved these changes

2021-09-20 15:16 UTC, merged