WIP migrate from CODEOWNERS to OWNERS
kyma-project/third-party-images pull request #196
Opened 2022-03-09 07:54 UTC by dennis-ge

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2022-03-09 07:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-project/third-party-images?pullRequest=196) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-project/third-party-images?pullRequest=196) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-project/third-party-images?pullRequest=196) it.</sub>

2022-03-10 13:02 UTC, klaudiagrz reviewed
Adding PK to the approvers :D

2022-03-10 13:02 UTC, klaudiagrz commented on OWNERS_ALIASES
> +
```suggestion
    - PK85
```

2022-03-10 13:31 UTC, Ressetkk commented
/test all

2022-03-10 13:47 UTC, Halamix2 commented
/retest

2022-03-11 12:18 UTC, Halamix2 commented
/retest

2022-03-15 07:12 UTC, dennis-ge commented
/retest

2022-03-15 09:51 UTC, lindnerby requested changes

2022-03-15 09:51 UTC, lindnerby commented on OWNERS_ALIASES
> +  observability-aprovers:
does this typo matter?

2022-03-15 09:51 UTC, lindnerby commented on jaeger-operator/OWNERS
> +  - observability-approvers
i guess it does ;)

2022-03-15 11:08 UTC, dennis-ge commented on jaeger-operator/OWNERS
> +  - observability-approvers
yes it does :D thanks!

2022-03-15 12:04 UTC, lindnerby approved these changes

2022-03-16 07:58 UTC, dbadura approved these changes

2022-03-16 08:04 UTC, wozniakjan approved these changes

2022-03-16 08:05 UTC, merged