build striped down otel collector image
kyma-project/third-party-images pull request #281
Opened 2022-11-23 10:16 UTC by rakesh-garimella

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2022-11-23 16:18 UTC, pbochynski requested changes
Wrong PR description.

2022-11-23 23:31 UTC, pbochynski reviewed
Add yourself as a codeowner.

2022-11-24 14:06 UTC, chrkl approved these changes

2022-11-24 14:11 UTC, pbochynski approved these changes

2022-11-24 14:14 UTC, merged